---
title: "Section 3 Video 1 : What is Principal Component Analysis? "
author: "Antoine Pissoort"
output: 
  html_document:  
    theme: readable  # Document Style
    highlight: tango # Syntax Highlighting
    number_sections: yes # Table Of Content numbering
    toc: yes  # Table Of Content
    toc_depth: 3  # Table Of Content depth
    df_print: paged # Print the data frames in a html table
---
  
  
# Automatic Packages Installing and Loading 
  
```{r setup}
knitr::opts_chunk$set(echo       = TRUE,
                      fig.height = 3.5,
                      fig.width  = 6)

packages <- c("tidyverse", "factoextra", "GGally")

## Install packages From CRAN if they are not installed.
for (p in packages) {
  if (p %in% rownames(installed.packages()) == FALSE) {
    install.packages(p, repos = 'http://cran.us.r-project.org')
  }
}
## Load the packages
for (p in packages)
  suppressPackageStartupMessages(
    library(p, quietly = TRUE, character.only = TRUE ) 
  )
```


# The Dataset : Decathlon 

```{r}
data(decathlon2, package = "factoextra")
decathlon2
```


**Order by rank**
```{r}
decathlon2 %>% rownames_to_column %>% arrange(Rank)
```



# Correct athlete names
```{r}
# TODO 
# decathlon2$athlete <- tolower(rownames(decathlon2))
```



# First visualization 


**Correlation plot**
```{r}
# Take only numric features that will be used for the PCA.
decathlon2_features <- decathlon2[, 1:10]

ggcorr(decathlon2_features, palette = "RdBu", label = TRUE)
```






